### PR TITLE
Add goofys 0.0.9 recipe

### PR DESCRIPTION
**Pull request by andrewgaul**

### CODE REVIEW

**Comment by andrewgaul** [comment]
This pull request actually passes all the PR checks, only failing the notability check due to GitHub API rate limiting.

**Comment by umireon** [comment]
I think programs build in Go should use `go_resources`. Example: [serf](https://github.com/Homebrew/homebrew-core/blob/4fd00963195f326e60faaf33e0c6d78817c5a844/Formula/serf.rb)

**Comment by andrewgaul** [comment]
@umireon Thanks for the pointer!  I have addressed all outstanding review comments.

**Comment by andrewgaul** [comment]
Travis fails for an unrelated reason:

```
Error: GitHub 

The GitHub credentials in the macOS keychain may be invalid.

Clear them with:

  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase

Or create a personal access token:

  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew

and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"

==> FAILED
```

**Comment by MikeMcQuaid** [comment]
I've restarted the build.

**Comment by andrewgaul** [comment]
@MikeMcQuaid Same issue.

**Comment by MikeMcQuaid** [comment]
Fixed CI issue. Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
