### PR TITLE
Delete unused formulae

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Delete all homebrew/fuse formulae that show no installations since analytics records began.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@bfontaine @DomT4 Any objections here?

**Comment by DomT4** [comment]
Think it has pretty much been @ilovezfs single-handedly maintaining this repo post-Dom, so if he's happy I'm a 👍.

**Comment by ilovezfs** [comment]
in the last 30 days
afuse 8 installs
archivemount 9
djmount 1
fuse-zip 10
mp3fs 4
ori 5
rofs-filtered 12
s3-backer 1

Since July
afuse 47
archivemount 67
djmount 34
fuse-zip 93
mp3fs 28
ori 39
ros-filtered 20
s3-backer 55

So I still think there's something off your script.

**Comment by MikeMcQuaid** [comment]
I went since analytics began so I think the statistical stuff is what's coming into play because it's based off 1% of sessions in that time. Those numbers are still low enough that if this was Homebre/homebrew-core that'd be a boneyard candidate.

**Comment by ilovezfs** [comment]
I'm wary to get rid of these because we're talking about access to people's data for each of these file systems.

**Comment by MikeMcQuaid** [comment]
Cool, will pass on this.

**Pull request closed without merging**
