### PR TITLE
gcsfuse 0.13.0

### PR DESCRIPTION
**Pull request by jacobsa**

### CODE REVIEW

**Comment by DomT4** [comment]
The error here is a known core issue, we _believe_. Should be fixed today/tomorrow, at which point I'll poke this back through CI.

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by DomT4** [comment]
@bfontaine There is no Jenkins CI here. Only Travis.

The current bug is a bit weird, trying to look into it but doesn't repro locally at all.

**Comment by jacobsa** [comment]
@DomT4: Any update on this? I can't tell for sure whether this is my bug...

**Comment by jacobsa** [comment]
I'm abandoning this in favor of #24, which is for a newer version of gcsfuse.

**Pull request closed without merging**
