### PR TITLE
Fix missing pycparser install

### PR DESCRIPTION
**Pull request by t-ionut**
This PR should fix the following error. Tested on OS X 10.10.5

```
[~] gitfs                                                                                                      
Traceback (most recent call last):
  File "/usr/local/bin/gitfs", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2991, in <module>
    @_call_aside
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 662, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 970, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 856, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycparser' distribution was not found and is required by cffi
```

### CODE REVIEW

**Comment by t-ionut** [comment]
Is there something wrong with the build process? I'm not familiar with Travis, but it looks like there are three different PRs (https://github.com/Homebrew/homebrew-fuse/pull/69 https://github.com/Homebrew/homebrew-fuse/pull/73 & https://github.com/Homebrew/homebrew-fuse/pull/75) sharing the same error:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
```

**Comment by umireon** [comment]
@t-ionut This is probably the effect of `sudo brew cask install osxfuse`, which may create `/usr/local/include` owned by root.
#85 should fix that.

**Comment by t-ionut** [comment]
@umireon no problem, I'll wait for #85 to be merged and rebase :smile:

**Comment by umireon** [comment]
The current formula of gitfs does not build when CLT is not installed: [build log](https://gist.github.com/umireon/6f7fa2e4a6b5f3bd132186136645fbf3)

This problem can be circumvented by this PR, but the root cause is still not clear.

**Comment by ilovezfs** [comment]
Yes, @umireon is right. The libffi problem should be reported upstream.

**Comment by umireon** [comment]
I think The resource sections should be reordered to match their dependency order (i.e. cffi comes before atomiclong).
This will make easier to investigate the problem (build log)[https://gist.github.com/umireon/fef4e7c4a3f9e39901af2432b4a3a705]

**Comment by umireon** [comment]
The problem in cffi is [reported at upstream](https://bitbucket.org/cffi/cffi/issues/171/pip-cffi-package-installation-falied-on).

**Comment by umireon** [comment]
PR created at upstream: https://bitbucket.org/cffi/cffi/pull-requests/73/able-to-build-on-macos-only-with-xcode-but/diff
Patch: https://bitbucket.org/api/2.0/repositories/cffi/cffi/pullrequests/73/patch

**Comment by umireon** [comment]
[cffi/cffi#73](https://bitbucket.org/cffi/cffi/pull-requests/73/able-to-build-on-macos-only-with-xcode-but/diff#comment-None) merged: this will fix the problem without CLT.

**Comment by MikeMcQuaid** [comment]
@umireon Anything else needed here?

**Comment by umireon** [comment]
@MikeMcQuaid Updating cffi will remove the need of CLT checking.
The author of cffi seems to preparing a new release of cffi.
Anything else would be fine.

**Comment by MikeMcQuaid** [comment]
Let's wait for the new release.

**Pull request closed without merging**
