### PR TITLE
rofs-filtered 1.7

### PR DESCRIPTION
**Pull request by honggoff**
rofs-filtered changed the build system to cmake.

### CODE REVIEW

**Comment by honggoff** [comment]
Version 1.6 and older fail to install on MacOS 10.12, see https://github.com/gburca/rofs-filtered/issues/18.

**Comment by fulldecent** [comment]
And... wow, using CMake is so much cleaner!

**Comment by honggoff** [comment]
@ilovezfs are there any objections to this? Since rofs-filtered switched build systems, the existing formula will not work for new releases. Also, until this is is merged, installation fails on MacOS 10.12

**Comment by fulldecent** [comment]
Bump.

**Pull request merged**
