### PR TITLE
Add btfs

### PR DESCRIPTION
**Pull request by cprecioso**

### CODE REVIEW

**Comment by cprecioso** [comment]
Mmm... The CI checks have failed, but it doesn't seem btfs' formula's fault

**Comment by DomT4** [comment]
Sorry for the delay here! If you rebase this against an up-to-date `master` branch it should pass this time, hopefully.

**Comment by cprecioso** [comment]
Done, failed again, still not btfs's fault

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-fuse/commit/5f654d3ec0bec90d4cc8c7c8b601429b70b32cab. Thank you for your contribution to Homebrew @cprecioso; we appreciate it! :smiley_cat:

**Pull request merged**
