### PR TITLE
ntfs-3g: Add HEAD option

### LINKED ISSUE #13: Add option to install ntfs-3g edge
The current version of `ntfs-3g` is not compatible with some Windows 10 security descriptors (http://wimlib.net/forums/viewtopic.php?f=1&t=4#p8). However, on their schedule this won't arrive to `stable` until 2016. Would it be possible to update the formula to allow building from the `edge` branch (http://sourceforge.net/p/ntfs-3g/ntfs-3g/ci/edge/tree/) with an optional switch?

### PR DESCRIPTION
**Pull request by cprecioso**
Closes #13

### CODE REVIEW

**Comment by dunn** [comment]
Minor audit failure:
```
==> brew audit homebrew/fuse/ntfs-3g					
Error: 1 problem in 1 formula
homebrew/fuse/ntfs-3g:
 * 10: Trailing whitespace was found

**Comment by cprecioso** [comment]
Done

**Comment by cprecioso** [comment]
bump

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-fuse/commit/c19596512c0155bdcf96ac0c24ae61e140a08166, Thank you for your contribution! :smiley_cat:

**Pull request closed without merging**
