### PR TITLE
Fix gitfs

### PR DESCRIPTION
**Pull request by gbeine**
Added missing dependencies
- raven
- contextlib2
- pycparser

Fixed dependency: pygit2 requries libgit 0.24.x (provided in my homebrew-extras)
Added a patch to make pygit2 work with libgit 0.24.2 instead of 0.24.1

### CODE REVIEW

**Comment by kontrafiktion** [comment]
I get

```Error: Invalid formula: /usr/local/Homebrew/Library/Taps/gbeine/homebrew-extras/phing.rb
phing: cannot load such file -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Requirements/php-meta-requirement
Error: Cannot tap gbeine/extras: invalid syntax in tap!
```

**Comment by gbeine** [comment]
I'll take a look at this issue...

**Comment by lemmycaution** [comment]
@kontrafiktion probably you don't have https://github.com/Homebrew/homebrew-php installed, which the line `phing: cannot load such file -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Requirements/php-meta-requirement` complains about.

**Comment by kontrafiktion** [comment]
Do I need homebrew-php for gitfs?

**Comment by fabanice** [comment]
brew install homebrew/fuse/gitfs
==> Installing gitfs from homebrew/fuse
==> Using the sandbox
==> Downloading https://github.com/PressLabs/gitfs/archive/0.4.5.1.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/gitfs-0.4.5.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/5c/79/5dae7494b9f5ed061cff9a8ab8d6e1f02db352f3facf907d9eb614fb80e9/virtualenv-15.0.2.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/gitfs--homebrew-virtualenv-15.0.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/gitfs--homebrew-virtualenv-20170327-27872-dcwt9g/target --single-version-externally-managed --
==> python -s /tmp/gitfs--homebrew-virtualenv-20170327-27872-dcwt9g/target/bin/virtualenv -p python /usr/local/Cellar/gitfs/0.4.5.1/libexec
==> Downloading https://files.pythonhosted.org/packages/86/8c/70aea8215c6ab990f2d91e7ec171787a41b7fbc83df32a067ba5d7f3324f/atomiclong-0.1.1.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/gitfs--atomiclong-0.1.1.tar.gz
==> /usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/gitfs--atomiclong-20170327-27872-1xr30uk/a
==> Downloading https://files.pythonhosted.org/packages/83/3c/00b553fd05ae32f27b3637f705c413c4ce71290aa9b4c4764df694e906d9/cffi-1.7.0.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/gitfs--cffi-1.7.0.tar.gz
==> /usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/gitfs--cffi-20170327-27872-1i4u9nx/cffi-1.
Last 15 lines from /Users/admin/Library/Logs/Homebrew/gitfs/04.pip:
  Removing source in /private/tmp/pip-sEZdWj-build
Command "/usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-sEZdWj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5mVYPZ-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/gitfs/0.4.5.1/libexec/include/site/python2.7/cffi" failed with error code 1 in /private/tmp/pip-sEZdWj-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-sEZdWj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5mVYPZ-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/gitfs/0.4.5.1/libexec/include/site/python2.7/cffi" failed with error code 1 in /private/tmp/pip-sEZdWj-build/

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
Fix gitfs https://github.com/Homebrew/homebrew-fuse/pull/100

Hello ! What is wrong with my commands sir ? TY ^^

**Comment by MikeMcQuaid** [comment]
This formula was imported into homebrew/core. If it's still a desirable change: please reopen it there. Thanks!

**Pull request closed without merging**
