### PR TITLE
gcsfuse 0.15.1

### PR DESCRIPTION
**Pull request by jacobsa**

### CODE REVIEW

**Comment by DomT4** [comment]
Ref: https://github.com/Homebrew/homebrew-fuse/commit/15482277b4c2691187a67c4b029c001116790abd#commitcomment-15352750.

We fixed one Travis error and now have another one. Working on it :sweat:.

**Comment by jacobsa** [comment]
Sounds like the travis problem was fixed with 4af98b4cbc411dda8a97b55c0d59486d120c87ca. Is there a way to trigger another run? I pushed a rebased commit; will that do it?

**Comment by jacobsa** [comment]
Oh, looks like it did. Great.

**Comment by DomT4** [comment]
See also: https://github.com/Homebrew/homebrew/pull/48000

After *that* though, we should finally have finished fixing this tap. Several minor breakages that only really impact a few taps around the same period has made it difficult to chase down everything.

**Comment by jacobsa** [comment]
Hah wow, thanks for chasing this all down. Broken CI builds are really a pain, because the issues compound.

**Comment by DomT4** [comment]
Would you mind rebasing here against the master, for what should hopefully be the final time? Thanks!

**Comment by jacobsa** [comment]
Done.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-fuse/commit/873ad48fd9ecf9879dcd117d438c343e578fbb03. The tap is functional again, hurrah. Thanks for bearing with us @jacobsa! :)

**Pull request closed without merging**
